(in-package :entzauberte-matrices)

(macrolet ((def-inv-low-level (name)
             (multiple-value-bind (lisp-name foreign-name)
                 (capi-wrapper-names name :lapack)
               `(defcfun (,lisp-name ,foreign-name) lapack-int
                  (layout lapack-order)
                  (n      lapack-int)
                  (a      :pointer)
                  (lda    lapack-int)
                  (ipiv   :pointer)))))
  (def-inv-low-level sgetri)
  (def-inv-low-level dgetri)
  (def-inv-low-level cgetri)
  (def-inv-low-level zgetri))

(macrolet ((def-inv-lisp (name lisp-type lufn invfn)
             `(progn
                (serapeum:-> ,name ((mat ,lisp-type))
                             (values (or (smat ,lisp-type) null) integer &optional))
                (defun ,name (a)
                  (let ((n (array-dimension a 0))
                        (acopy (copy-array a)))
                    (with-foreign-object (ipivptr :int n)
                      (with-array-pointers ((aptr acopy))
                        (let ((info (,lufn  :row-major n n aptr n ipivptr)))
                          (if (zerop info)
                              (let ((info (,invfn :row-major n aptr n ipivptr)))
                                (if (zerop info)
                                    (values acopy 0)
                                    (values nil info)))
                              (values nil info))))))))))
  (def-inv-lisp inv-rs-unsafe single-float %sgetrf %sgetri)
  (def-inv-lisp inv-rd-unsafe double-float %dgetrf %dgetri)
  (def-inv-lisp inv-cs-unsafe (complex single-float) %cgetrf %cgetri)
  (def-inv-lisp inv-cd-unsafe (complex double-float) %zgetrf %zgetri))

(serapeum:-> invert ((mat *))
             (values (or (smat *) null) integer &optional))
(declaim (inline invert))
(defun invert (m)
  "Compute \\(M^{-1}\\) using \\(LU\\) factorization. Returns
@c((values inv infocode)) where @c(inv) can be @c(NIL) if \\(LU\\)
factoirization or inversion routine fails."
  (unless (= (array-dimension m 0)
             (array-dimension m 1))
    (error "Cannot invert a matrix: non-square matrix"))
  (cond
    ((eq (array-element-type m) 'single-float)
     (inv-rs-unsafe m))
    ((eq (array-element-type m) 'double-float)
     (inv-rd-unsafe m))
    ((equalp (array-element-type m) '(complex single-float))
     (inv-cs-unsafe m))
    ((equalp (array-element-type m) '(complex double-float))
     (inv-cd-unsafe m))
    (t
     (error "Cannot invert a matrix: Unknown array element type"))))
