(in-package :entzauberte-matrices)

(macrolet ((def-solver-low-level (name)
             (multiple-value-bind (lisp-name foreign-name)
                 (capi-wrapper-names name :lapack)
               `(defcfun (,lisp-name ,foreign-name) lapack-int
                  (layout lapack-order)
                  (n      lapack-int)
                  (nrhs   lapack-int)
                  (a      :pointer)
                  (lda    lapack-int)
                  (ipiv   :pointer)
                  (b      :pointer)
                  (ldb    lapack-int)))))
  (def-solver-low-level sgesv)
  (def-solver-low-level dgesv)
  (def-solver-low-level cgesv)
  (def-solver-low-level zgesv))

(macrolet ((def-solve (name low-level-fn lisp-type)
             `(progn
                (serapeum:-> ,name ((mat ,lisp-type)
                                    (mat ,lisp-type))
                             (values (or (smat ,lisp-type) null) integer &optional))
                (defun ,name (a b)
                  (let ((acopy (copy-array a))
                        (bcopy (copy-array b))
                        (n     (array-dimension a 0))
                        (nrhs  (array-dimension b 1)))
                    (with-array-pointers ((aptr acopy)
                                          (bptr bcopy))
                      (with-foreign-object (ipivptr 'lapack-int n)
                        (let ((info (,low-level-fn :row-major n nrhs aptr n 
                                                   ipivptr bptr nrhs)))
                          (declare (type fixnum info))
                          (if (zerop info)
                              (values bcopy 0)
                              (values nil info))))))))))
  (def-solve solve-rs-unsafe %sgesv single-float)
  (def-solve solve-rd-unsafe %dgesv double-float)
  (def-solve solve-cs-unsafe %cgesv (complex single-float))
  (def-solve solve-cd-unsafe %zgesv (complex double-float)))

(serapeum:-> solve ((mat *) (mat *))
             (values (or (smat *) null) integer &optional))
(declaim (inline solve))
(defun solve (a b)
  "Solve an equation \\(AX = B\\). This function uses @c(transpose)
internally. Return @c((values X infocode)) where @c(X) may be @c(NIL)
if the solver fails."
  (assert (= (array-dimension a 0)
             (array-dimension a 1)
             (array-dimension b 0)))
  (funcall
   (cond
     ((eq (array-element-type a) 'single-float)
      #'solve-rs-unsafe)
     ((eq (array-element-type a) 'double-float)
      #'solve-rd-unsafe)
     ((equalp (array-element-type a) '(complex single-float))
      #'solve-cs-unsafe)
     ((equalp (array-element-type a) '(complex double-float))
      #'solve-cd-unsafe)
     (t
      (error "Cannot solve an equation: unknown array element type")))
   a b))
